// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object FlutterVolumeListenerPluginPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()
private open class FlutterVolumeListenerPluginPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}

val FlutterVolumeListenerPluginPigeonMethodCodec = StandardMethodCodec(FlutterVolumeListenerPluginPigeonCodec())



private class FlutterVolumeListenerPluginPigeonStreamHandler<T>(
    val wrapper: FlutterVolumeListenerPluginPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface FlutterVolumeListenerPluginPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class VolumeChangeStreamHandler : FlutterVolumeListenerPluginPigeonEventChannelWrapper<Double> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: VolumeChangeStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.flutter_volume_listener.FlutterVolumeListenerEventApi.volumeChange"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = FlutterVolumeListenerPluginPigeonStreamHandler<Double>(streamHandler)
      EventChannel(messenger, channelName, FlutterVolumeListenerPluginPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from FlutterVolumeListenerPluginPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<Double>) {}

override fun onCancel(p0: Any?) {}
}
      
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FlutterVolumeListenerHostApi {
  fun getVolume(callback: (Result<Double>) -> Unit)

  companion object {
    /** The codec used by FlutterVolumeListenerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      FlutterVolumeListenerPluginPigeonCodec()
    }
    /** Sets up an instance of `FlutterVolumeListenerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FlutterVolumeListenerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_volume_listener.FlutterVolumeListenerHostApi.getVolume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getVolume{ result: Result<Double> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FlutterVolumeListenerPluginPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(FlutterVolumeListenerPluginPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
